# Generated by Django 4.2 on 2025-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PacketLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("src_ip", models.GenericIPAddressField()),
                ("dst_ip", models.GenericIPAddressField()),
                ("protocol", models.CharField(max_length=10)),
                ("bytes_in", models.IntegerField()),
                ("bytes_out", models.IntegerField()),
                ("packets_in", models.IntegerField()),
                ("packets_out", models.IntegerField()),
                ("host", models.CharField(max_length=50)),
            ],
        ),
    ]
