# Generated by Django 4.2 on 2025-02-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="logdata_dong",
            new_name="log_data",
        ),
    ]
